# Generated by Django 6.0.1 on 2026-01-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobappli',
            old_name='applied_date',
            new_name='apldate',
        ),
        migrations.RenameField(
            model_name='jobappli',
            old_name='company_name',
            new_name='comname',
        ),
        migrations.RenameField(
            model_name='jobappli',
            old_name='job_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='jobappli',
            old_name='job_title',
            new_name='title',
        ),
    ]
