# Generated by Django 6.0.1 on 2026-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_applied_date_jobappli_apldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobappli',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
