# Generated by Django 6.0.1 on 2026-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobappli',
            old_name='deadline',
            new_name='examdate',
        ),
        migrations.AddField(
            model_name='jobappli',
            name='ctc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
